services:
  app:
    build:
      context: .
    environment:
      OIDC_ENABLED: "true"
      OIDC_ISSUER: http://7f000001.nip.io:5556/dex
      OIDC_CLIENT_ID: example-app
      OIDC_CLIENT_SECRET: ZXhhbXBsZS1hcHAtc2VjcmV0
      OIDC_SCOPE: openid profile email
      OIDC_APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key-here
    ports:
      - 3000:3000
    links:
      - oidc-server:7f000001.nip.io

  oidc-server:
    image: dexidp/dex:v2.43.1-alpine
    ports:
      - 5556:5556
    domainname: 7f000001.nip.io
    configs:
      - source: config.yaml
        target: /etc/dex/config.docker.yaml
configs:
  config.yaml:
    content: |
      issuer: http://7f000001.nip.io:5556/dex
      storage:
        type: sqlite3
        config:
          file: /var/dex/dex.db
      web:
        http: 0.0.0.0:5556
      staticClients:
        - id: example-app
          redirectURIs:
            - 'http://localhost:3000/api/auth/callback/dex'
          name: 'Example App'
          secret: ZXhhbXBsZS1hcHAtc2VjcmV0
      connectors:
        - type: mockCallback
          id: mock
          name: Example
      enablePasswordDB: true
      staticPasswords:
      - email: "user01@example.localhost"
        # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "user01"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      - email: "user02@example.localhost"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "user02"
        userID: "a4588bda-8303-458e-965e-b9ae039ef7b7"
      oauth2:
        skipApprovalScreen: true
