apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-esg-app
  namespace: kube-esg
  labels:
    app: kube-esg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-esg-app
  template:
    metadata:
      labels:
        app: kube-esg-app
    spec:
      serviceAccountName: kube-esg-app
      containers:
      - name: app
        image: kube-esg-app:latest
        imagePullPolicy: Never  # For kind cluster with local images
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: OIDC_ENABLED
          value: "true"
        - name: OIDC_CLIENT_ID
          value: "example-app"
        - name: OIDC_SCOPE
          value: "openid profile email"
        - name: OIDC_APP_URL
          value: "http://localhost:3000"
        - name: NEXTAUTH_URL
          value: "http://localhost:3000"
        - name: OIDC_ISSUER
          value: "http://7f000001.nip.io:5556/dex"
        - name: OIDC_AUTHORIZATION_ENDPOINT
          value: "http://7f000001.nip.io:5556/dex/auth"
        - name: OIDC_TOKEN_ENDPOINT
          value: "http://dex.kube-esg.svc.cluster.local:5556/dex/token"
        - name: OIDC_JWKS_URI
          value: "http://dex.kube-esg.svc.cluster.local:5556/dex/keys"
        - name: OIDC_USERINFO_ENDPOINT
          value: "http://dex.kube-esg.svc.cluster.local:5556/dex/userinfo"
        - name: OIDC_CLIENT_SECRET
          value: "ZXhhbXBsZS1hcHAtc2VjcmV0"
        - name: NEXTAUTH_SECRET
          value: "your-secret-key-here"
        # Optional: Uncomment to filter namespaces by label presence in UI
        # - name: TARGET_LABEL_NAME
        #   value: "managed-by"
        # Optional: Uncomment to configure shutdown days (default: 7)
        # - name: SHUTDOWN_DAYS
        #   value: "7"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-esg-app
  namespace: kube-esg
  labels:
    app: kube-esg-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    name: http
  selector:
    app: kube-esg-app