apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-esg-app
  namespace: kube-esg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-esg-namespace-reader
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-esg-namespace-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-esg-namespace-reader
subjects:
- kind: ServiceAccount
  name: kube-esg-app
  namespace: kube-esg